#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and
i=0
while [ "$i" -lt "10" ]
do
	i+$((i+1))
	if [ "$i" -eq "8" ]
	then
		echo "good luck"
	elif [ "$i" -eq "4" ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
done
