#!/usr/bin/env bash
#The content of the current directory
In a list format
Where only the part of the name after the first dash is displayed (refer to the example)
list=$(ls)
for OUTPUT in $list
do
	echo "$OUTPUT" | cut -d - -f "2-"
done
